### ISSUE TITLE
Deprecate branch 3.0.0

### ISSUE THREAD

**Issue by Plou** [Inouit/dummy#21]
Once 4.0 is stable enought

**Comment by Plou** [comment]
Do we rename this repository and create a new empty project from branch 4 ?

**Comment by toofff** [comment]
I vote for a branch 4 because it is an evolution of the project.

**Comment by Gregcop1** [comment]
I can't agree more. It's an (r)evolution. 😛

**Comment by Plou** [comment]
Good !

**Comment by toofff** [comment]
If the opinion of greg enough to make a decision, it is useless to make a issue..

**Comment by Plou** [comment]
3 out of 5 is.

**Comment by Plou** [comment]
Oops, branch 3 isn't deprecated yet

**Comment by Plou** [comment]
4.0 is out !
