### ISSUE TITLE
Rework the scss to match guidelines

### ISSUE THREAD

**Issue by Plou** [Inouit/dummy#25]

**Comment by Plou** [comment]
Properties positions, formating, and comments annotations

**Comment by Gregcop1** [comment]
The main part of the job is done in 4b99f859eae19fdba435826f03e361ffa6f1f9e5 
We should separate some rules of "_reset.scss" in a separate file "_globals.scss" maybe

**Comment by Plou** [comment]
After 3b75b65 Some rewriting left but mostly documenting.

**Comment by Plou** [comment]
Done da139297
