### ISSUE TITLE
Think about a grunt configuration file

### ISSUE THREAD

**Issue by Plou** [Inouit/dummy#28]
Could be nice to ease cms / frameworks integration

**Comment by toofff** [comment]
This is not what one already?

**Comment by Plou** [comment]
I'm thinking of a `localconf.json` with only context specific configuration. I'm not sure how it may be done.

**Comment by toofff** [comment]
When we put the dummy in one of our projects, it becomes part we just change according to our need.

At the moment I do not see what could serve this part.

**Comment by Gregcop1** [comment]
That's why package.json exist, no? Describe contextual info for the project

**Comment by Plou** [comment]
I'm talking about this part which could be improved I guess: https://github.com/Inouit/dummy/blob/3.0.2/grunt/gruntfile.coffee#L32

**Comment by Gregcop1** [comment]
You're right, we should have a separate Json, readed as the package.json (grunt.file.readJSON) and created by the installation script depending of the technology
