### ISSUE TITLE
Publish dummy on npm ?

### ISSUE THREAD

**Issue by Plou** [Inouit/dummy#32]
Create a `package.json`

**Comment by Gregcop1** [comment]
is it really justified to "bublich" dummy on npm ? I think it's a contribution to npm repo's pollution.
However to simplify internal usage, may be we can use [npm private module](https://www.npmjs.com/private-modules) or a [free alternative](http://fiznool.com/blog/2015/05/20/an-alternative-to-npm-private-modules/)

**Comment by Plou** [comment]
Yep, let's not bublish it. @toofff agrees too.
