### ISSUE TITLE
Try the ITCSS method on dummy

### ISSUE THREAD

**Issue by Gregcop1** [Inouit/dummy#44]

**Comment by Plou** [comment]
Code and structure on [itcss](https://github.com/Inouit/dummy/tree/23f796b6c7d351006a7724aad5615d87e481d3c6) branch are ready to go.
A notice and some links are missing in order to merge into master. 
Before we make it the next dummy we have to schedule a internal dev meeting.

**Comment by Plou** [comment]
The notice will be in our Inouit/styleguide #9

I just added a link to the Harry Robert's talk which will be replace with the link to our styleguide

**Comment by Plou** [comment]
Il reste encore des petits changements de nom à effectuer pour mieux coller à ITCSS, notamment au niveaux des objets qui ont des noms de composants et pas de comportement (ex: .nav à remplacer par .horizontal-list)
