### ISSUE TITLE
Clean path variables from gruntfile

### ISSUE THREAD

**Issue by Plou** [Inouit/dummy#51]
A configuration file should be created (and used :p).
The main advantage is to have only one place to look for common customization. It'll help to be more welcoming to new users.

It could be something like that:
``` coffee
js:
  source: '../js/src/'
  dest: '../js/'
css:      
  source  : '../css/src/'
  dest : '../css/'
sync:
  files: [
    '../*.html'
    '../css/*.css'
    '../js/*.js'
    '../img/**'
  ]
  server: '../'
  proxy: false
  open: false
autoprefixer:
  browsers: 'last 3 version'
```

**Comment by Gregcop1** [comment]
Some project like the putaindecode website have two conf files :
- paths.coffee
- vars/options.coffee
On tiny project, it can be useless but on huge project with more complex grunt tasks, why not

**Comment by Plou** [comment]
We can have two main object in this file: path & options will make it ready to be allotted in two files as we need.
